### ISSUE TITLE
Navbar Refactor & Improvements

### ISSUE THREAD

**Issue by SirSeim** [SirSeim/SPFY#16]
![image](https://cloud.githubusercontent.com/assets/3513446/19937424/6e9c6d52-a0de-11e6-9948-352985650099.jpg)

**Comment by SirSeim** [comment]
## Alerts
- Checkbox to confirm the alert has been taken care of
- Label showing the type of notification
- Textual comment detailing what needs to happen

## Profile/Account
- Links to pages where User information can be entered/modified
- If the User is of high enough ranking, they also get access to System configuration
  - General contains general configurations that don't fit under some other category
  - Labels contains the list of labels that can be attached to notifications and client profiles
    - Set color and associated text for them
- Logout button which clears the `authorization` entry in `localStorage`

**Comment by cf7** [comment]
Are we thinking that the "Profile" dropdown on the top right will become the SPY staff's name when they login?

**Comment by mreid10** [comment]
moved to #25
