### ISSUE TITLE
Front Desk > Enrollment

### ISSUE THREAD

**Issue by SirSeim** [SirSeim/SPFY#17]
![img_1213](https://cloud.githubusercontent.com/assets/3513446/19938073/e74caa26-a0e0-11e6-8812-baae64553756.JPG)

**Comment by SirSeim** [comment]
## Activities for Today

- By default, an activity lists the number of participants for today
- When typing in `Search or Add` Participants already enrolled are filtered
  - Clients that are not enrolled and match the search filter show up in the list above the _Participants_ header, along with a plus button which will enroll them in that activity
- A search bar within the Activities view filters which events are viewed by their name, or by a participant in that activity
  - _Example_: searching **John** will show activities that either contain the characters **John** or show activities that contain a person that has the characters **John**, highlighting that person and showing that/those names at the top of the list
    - _Images to come_
- Clicking on any Clients name brings up the modal profile view for that client
- Attached to each client profile row is a checkbox where staff can checkoff if the youth has actually "gone" to the activity, they said this is important for helping them know which youth sign up but don't attend
- At most 3 activities can be shown on the view at any point, additional ones must be paginated
  - ◀️ and ▶️ arrows are on the left and right side _respectively_ of the Activities view
    - _Bonus_: Animate the transition between views of Activities
    - Smaller screen sizes like iPads should be limited to 2 or even 1 Activity

**Comment by lkonchan** [comment]
![img_5250 jpg](https://cloud.githubusercontent.com/assets/10541730/19952482/e5628ee6-a122-11e6-8e30-14c672740a76.jpeg)

**Comment by SirSeim** [comment]
**POST** `/api/dropins/{dropinID}/activities` route
Example `application/json` body:

```json
{
    "activities": [
        {
            "id": 2,
            "room": "Main Office",
            "startTime": "11:00:00",
            "endTime": "14:00:00"
        },
        {
            "id": 3,
            "comments": "Less staff than usual"
        }
    ]
}
```

Only `id` is required for adding an activity to a dropin
Option fields are `room`, `comments`, `startTime`, and `endTime`
All other options or omissions are forbidden

**Comment by SirSeim** [comment]
http://stackoverflow.com/questions/6323338/jquery-ajax-posting-json-to-webservice
An example of posting JSON to the server with JQuery

**Comment by SirSeim** [comment]
To enroll a client in a dropin activity:
POST `/api/dropins/{dropinID}/activities/{activityID}/enrollment` with payload:
```json
{
  "clients": [
    1,7
  ]
}
```
Returns:
```json
{
  "statusCode": 200,
  "message": "Successfully added enrollment for activity for dropin!",
  "result": {
    "dropin": 6,
    "activity": 5,
    "clients": [
      1,
      7
    ]
  }
}
```

**If client IDs are not being returned**, there are a variety of reasons why:
- That dropin/activity combo has not been registered _(Aka, you need to add that activity to that dropin)_
- That/those clients have already been registered with that dropin/activity combo

**Comment by lkonchan** [comment]
- [x] Auto population of activity bar based on current drop in
- [x] ^^ additionally should append "active" property to the list button in addActivity modal
- [x] Populate **ActivitiesTable** with enrolled clients & their info
- [x] Clean up ugly delete buttons
- [x] Enroll button posts new client
- [x] ^^ search bar to find people to add **who aren't currently in the list**
- [x] remove (unenroll) people from the activity

**Comment by lkonchan** [comment]
- [x] need to fix "disabled" bug in addActivity modal
- [x] removal of activity needs to be reflected in the database

**Comment by SirSeim** [comment]
Its all over!
