### ISSUE TITLE
Files

### ISSUE THREAD

**Issue by SirSeim** [SirSeim/SPFY#20]
We need to be able to upload and download files from the site. Details are sparse because we know so little about what it takes to do files. Post comments and/or pictures as we understand more about the process.

**Comment by IrakliK** [comment]
![img_8352](https://cloud.githubusercontent.com/assets/6171908/19952309/841e7a4c-a121-11e6-8f2f-077d616e41e5.JPG)

@dondi mentioned how we should first work on the routing and getting files within the web service first. Finally, once we have that set we can then research about the three choices in the image (a) giving the db a path to the file (b) using the blob method (c) working with mongo (which handles documents better).

@dondi prefers choice (b). We should research about this first.

**Comment by IrakliK** [comment]
This is what I found,

For example, suppose you have a table containing the file name of an image and you also want to store the image in a bytea column:

`CREATE TABLE images (imgname text, img bytea);`

To insert an image, you would use:

```
File file = new File("myimage.gif");
FileInputStream fis = new FileInputStream(file);
PreparedStatement ps = conn.prepareStatement("INSERT INTO images VALUES (?, ?)");
ps.setString(1, file.getName());
ps.setBinaryStream(2, fis, file.length());
ps.executeUpdate();
ps.close();
fis.close();
```
