### ISSUE TITLE
View Client > Case Plan

### ISSUE THREAD

**Issue by cf7** [SirSeim/SPFY#38]
The client profile needs a tab for a case plan . . .

There only needs to be one case plan per client, but the option for multiple notes per case plan
It will be used for setting goals and discussing ways the youth can reach them and helping CM’s track their progress

It doesn’t have to be fancy yet, just a way for them to have goals in writing and have a concrete idea for what youth want to work on

**Comment by IrakliK** [comment]
- [ ] Test Route and Database

**Comment by IrakliK** [comment]
DONE!
