### ISSUE TITLE
Create New Activity

### ISSUE THREAD

**Issue by cf7** [SirSeim/SPFY#47]
High priority:

SPY staff need a process to create new activities entirely. (This is different from adding an activity to a drop-in.)

Use Case: An LMU student group comes in and wants to teach programming to the youth. Staff say, "Great, we'll create a new activity on the database so youth can sign up for it."
• name of activity
• location
• times it will be available (won't need to designate day because that is what staff determines when they create drop-in)
• what "program" will it belong to? (Digital Arts Lab, Employment, Medical, . . . etc.)

Whoever works on this will have to decide whether creating a new activity should be a whole new page or not or just another modal on an existing page or any other design choice . . . but it would be good to review SPY feedback to see where exactly they wanted this . . .

We currently only have a route for this issue. The interface needs to be started.

**Comment by NAnguiano** [comment]
Done.
